"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _home_admin_data from './home-admin-data.bones.json'
import _home_admin from './home-admin.bones.json'
import _home_archive_data from './home-archive-data.bones.json'
import _home_archive from './home-archive.bones.json'
import _home_files from './home-files.bones.json'
import _home_pools_data from './home-pools-data.bones.json'
import _home_pools from './home-pools.bones.json'
import _sheet_grid from './sheet-grid.bones.json'
import _tools_splitter from './tools-splitter.bones.json'

registerBones({
  "home-admin-data": _home_admin_data,
  "home-admin": _home_admin,
  "home-archive-data": _home_archive_data,
  "home-archive": _home_archive,
  "home-files": _home_files,
  "home-pools-data": _home_pools_data,
  "home-pools": _home_pools,
  "sheet-grid": _sheet_grid,
  "tools-splitter": _tools_splitter,
})
