import { Hono } from "hono";
import type { Env, Row, SheetFile } from "../lib/shared";
import { requireAuth } from "../lib/session";
import { rpc } from "../lib/do";

export const files = new Hono<{ Bindings: Env; Variables: { uid: string } }>();
const fileId = () => crypto.randomUUID().replaceAll("-", "").slice(0, 12);
async function owned(c: any, id: string) { const found = await rpc(c.env.INDEX, "global", "file", { id }); return found && found.owner_id === c.get("uid") && !found.archived ? JSON.parse(found.data) as SheetFile : null; }
files.use("/*", requireAuth);
files.get("/", async (c) => c.json(await rpc(c.env.INDEX, "global", "files", { uid: c.get("uid") })));
files.post("/", async (c) => { const body = await c.req.json<Partial<SheetFile>>(); const file: SheetFile = { id: fileId(), name: String(body.name || "Untitled"), type: body.type === "fb_cookie" ? "fb_cookie" : "fb_cookie", password: String(body.password || "dgddigital"), poolEnabled: body.poolEnabled !== false, createdAt: Date.now(), updatedAt: Date.now(), rowCount: 0, dataCount: 0 }; await rpc(c.env.INDEX, "global", "register", { uid: c.get("uid"), file }); await rpc(c.env.FILES, file.id, "init", { file, rows: [] }); return c.json(file); });
files.put("/:id", async (c) => { const file = await owned(c, c.req.param("id")); if (!file) return c.json({ error: "file not found" }, 404); const body = await c.req.json<Record<string, unknown>>(); for (const k of ["name", "type", "columns", "password", "poolEnabled"]) if (k in body) (file as any)[k] = body[k]; file.updatedAt = Date.now(); await rpc(c.env.FILES, file.id, "save", { file, rows: await rpc(c.env.FILES, file.id, "rows") }); await rpc(c.env.INDEX, "global", "register", { uid: c.get("uid"), file }); return c.json(file); });
files.delete("/:id", async (c) => { const file = await owned(c, c.req.param("id")); if (!file) return c.json({ error: "file not found" }, 404); file.deletedAt = Date.now(); await rpc(c.env.INDEX, "global", "archive", { id: file.id, archived: true, file }); return c.json({ ok: true }); });
files.get("/:id/rows", async (c) => { const file = await owned(c, c.req.param("id")); return file ? c.json(await rpc(c.env.FILES, file.id, "rows")) : c.json({ error: "file not found" }, 404); });
files.get("/:id/full", async (c) => { const file = await owned(c, c.req.param("id")); return file ? c.json({ file, rows: await rpc(c.env.FILES, file.id, "rows"), logs: [], undo: [], redo: [], seq: 0 }) : c.json({ error: "file not found" }, 404); });
files.put("/:id/persist", async (c) => { const file = await owned(c, c.req.param("id")); if (!file) return c.json({ error: "file not found" }, 404); const body = await c.req.json<{ rows?: Row[]; action?: string; dataCount?: number }>(); const rows = body.rows || []; if (body.dataCount !== undefined) file.dataCount = body.dataCount; file.rowCount = rows.length; file.updatedAt = Date.now(); const saved = await rpc(c.env.FILES, file.id, "save", { file, rows, action: body.action || "edit" }); await rpc(c.env.INDEX, "global", "register", { uid: c.get("uid"), file }); return c.json({ ok: true, seq: saved.seq, file }); });
files.put("/:id/append", async (c) => { const file = await owned(c, c.req.param("id")); if (!file) return c.json({ error: "file not found" }, 404); const body = await c.req.json<{ base: number; ops: { rowIdx: number; cols: Record<string, string> }[]; dataCount?: number; action?: string }>(); if (!Number.isInteger(body.base) || !Array.isArray(body.ops) || body.ops.length > 10000) return c.json({ error: "invalid append payload" }, 400); const rows = await rpc(c.env.FILES, file.id, "rows") as Row[]; if (body.base !== Number((await rpc(c.env.FILES, file.id, "history")).length)) return c.json({ error: "version conflict" }, 409); for (const op of body.ops) { while (rows.length <= op.rowIdx) rows.push({}); rows[op.rowIdx] = { ...rows[op.rowIdx], ...op.cols }; } file.rowCount = rows.length; file.updatedAt = Date.now(); const saved = await rpc(c.env.FILES, file.id, "save", { file, rows, action: body.action || "append" }); await rpc(c.env.INDEX, "global", "register", { uid: c.get("uid"), file }); return c.json({ ok: true, seq: saved.seq, file }); });
export { owned };
