import { Hono } from "hono";
import type { Env } from "../lib/shared";
import { requireAuth } from "../lib/session";
import { rpc } from "../lib/do";
import { owned } from "./files";
export const history = new Hono<{ Bindings: Env; Variables: { uid: string } }>();
history.use("/:id/history/*", requireAuth);
history.get("/:id/history", async (c) => { const f = await owned(c, c.req.param("id")); return f ? c.json(await rpc(c.env.FILES, f.id, "history")) : c.json({ error: "file not found" }, 404); });
history.get("/:id/history/:v", async (c) => { const f = await owned(c, c.req.param("id")); return f ? c.json(await rpc(c.env.FILES, f.id, "version", { v: Number(c.req.param("v")) })) : c.json({ error: "file not found" }, 404); });
history.post("/:id/history/:v/:action", async (c) => { const f = await owned(c, c.req.param("id")); if (!f) return c.json({ error: "file not found" }, 404); const v = Number(c.req.param("v")); const action = c.req.param("action"); if (action === "name") { const body = await c.req.json<{ name?: string }>(); return c.json(await rpc(c.env.FILES, f.id, "name", { v, label: body.name })); } if (action === "restore") return c.json(await rpc(c.env.FILES, f.id, "restore", { v })); return c.json({ error: "unsupported action" }, 400); });
