import type { Context, Next } from "hono";
import type { Env } from "./shared";
import { rpc } from "./do";

const enc = new TextEncoder();
const b64 = (v: ArrayBuffer | string) => btoa(typeof v === "string" ? v : String.fromCharCode(...new Uint8Array(v))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
const unb64 = (v: string) => atob(v.replace(/-/g, "+").replace(/_/g, "/") + "===".slice((v.length + 3) % 4));
async function key(secret: string, usage: ("sign" | "verify")[]) { if (!secret) throw new Error("SESSION_SECRET missing"); return crypto.subtle.importKey("raw", enc.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, usage); }
export async function signSession(uid: string, secret: string) { if (!secret) throw new Error("SESSION_SECRET missing"); const body = b64(JSON.stringify({ uid, exp: Date.now() + 30 * 86400000 })); const sig = b64(await crypto.subtle.sign("HMAC", await key(secret, ["sign"]), enc.encode(body))); return `${body}.${sig}`; }
export async function verifySession(token: string, secret: string) { if (!secret) throw new Error("SESSION_SECRET missing"); const [body, sig] = token.split("."); if (!body || !sig) return null; try { const valid = await crypto.subtle.verify("HMAC", await key(secret, ["verify"]), Uint8Array.from(unb64(sig), (c) => c.charCodeAt(0)), enc.encode(body)); if (!valid) return null; } catch { return null; } try { const data = JSON.parse(unb64(body)); return data.exp > Date.now() ? { uid: String(data.uid) } : null; } catch { return null; } }
// ponytail: direct cross-origin calls (pages.dev → railway.app) need SameSite=None (Lax cookies never ride fetch); None requires Secure, so http local dev keeps Lax
export function cookie(token: string, maxAge = 2592000, secure = true) { return `ss_session=${token}; Path=/; HttpOnly;${secure ? " Secure; SameSite=None" : " SameSite=Lax"}; Max-Age=${maxAge}`; }
// TEMPORARY e2e debug (remove after diagnosing the create-file 401): log which branch rejects.
export async function requireAuth(c: Context<{ Bindings: Env; Variables: { uid: string } }>, next: Next) { const rawCookie = c.req.header("Cookie") || ""; const token = rawCookie.match(/(?:^|;\s*)ss_session=([^;]+)/)?.[1]; if (!c.env.SESSION_SECRET) return c.json({ error: "Server configuration error" }, 500); if (!token) { console.error(`[auth-debug] no token hdr=${JSON.stringify(rawCookie.slice(0, 80))}`); return c.json({ error: "Not authenticated" }, 401); } let session: { uid: string } | null = null; try { session = await verifySession(token, c.env.SESSION_SECRET); } catch { console.error("[auth-debug] verify threw"); return c.json({ error: "Not authenticated" }, 401); } if (!session) { console.error("[auth-debug] verify null"); return c.json({ error: "Not authenticated" }, 401); } try { const dbSession: any = await rpc(c.env.INDEX, "global", "getSession", { token }); if (!dbSession) { console.error("[auth-debug] no db session"); return c.json({ error: "Not authenticated" }, 401); } const user: any = await rpc(c.env.INDEX, "global", "user", { id: session.uid }); if (!user) { console.error("[auth-debug] no user"); return c.json({ error: "Not authenticated" }, 401); } if (user.banned) return c.json({ error: "account banned" }, 403); } catch { console.error("[auth-debug] db threw"); return c.json({ error: "Not authenticated" }, 401); } c.set("uid", session.uid); return next(); }
export const isAdmin = (env: Env, uid: string) => (env.ADMIN_IDS || "").split(",").map((v) => v.trim()).includes(uid);
