import { Hono } from "hono";
import type { Env, SheetFile } from "../lib/shared";
import { FILE_ROW_LIMIT } from "../lib/shared";
import { selectFeedRows } from "../lib/shared";
import { requireAuth, isAdmin } from "../lib/session";
import { rpc } from "../lib/do";
import { ldCounts, decorateHoldState, feedPools, removePoolRows, heldInRows, heldBlock, poolId } from "./files";
export const admin = new Hono<{ Bindings: Env; Variables: { uid: string } }>();
admin.use("/*", requireAuth);
admin.use("/*", async (c, next) => isAdmin(c.env, c.get("uid")) ? next() : c.json({ error: "admin access required" }, 403));
const shapeUser = (env: Env, u: any) => ({ id: String(u.user_id), name: u.name || "", username: u.username || "", photoUrl: u.photo_url || null, phone: u.phone || null, banned: !!u.banned, createdAt: u.created_at, fileCount: u.fileCount ?? 0, archivedCount: u.archivedCount ?? 0, isAdmin: isAdmin(env, String(u.user_id)) });
admin.get("/stats", async (c) => c.json(await rpc(c.env.INDEX, "global", "stats")));
admin.get("/users", async (c) => { const users = await rpc(c.env.INDEX, "global", "adminUsers") as any[]; return c.json(users.map((u) => shapeUser(c.env, u))); });
admin.get("/users/search", async (c) => { const q = (c.req.query("q") || "").trim().slice(0, 64); const users = await rpc(c.env.INDEX, "global", "adminUsersSearch", { q }) as any[]; return c.json(users.map((u) => shapeUser(c.env, u))); });
admin.get("/user/:id", async (c) => { const id = c.req.param("id"); if (!id || id.length > 64) return c.json({ error: "invalid id" }, 400); const u = await rpc(c.env.INDEX, "global", "adminUser", { id }) as any; if (!u) return c.json({ error: "user not found" }, 404); const files = await rpc(c.env.INDEX, "global", "files", { uid: id, archived: "all" }); return c.json({ ...shapeUser(c.env, u), files }); });
admin.get("/user/:id/archive", async (c) => c.json(await rpc(c.env.INDEX, "global", "files", { uid: c.req.param("id"), archived: 1 })));
admin.post("/user/:id/archive/:fileId/restore", async (c) => { const found: any = await rpc(c.env.INDEX, "global", "file", { id: c.req.param("fileId") }); if (!found || found.owner_id !== c.req.param("id") || !found.archived) return c.json({ error: "not found" }, 404); const file = JSON.parse(found.data); delete file.deletedAt; file.lastAction = "restored"; await rpc(c.env.INDEX, "global", "archive", { id: file.id, archived: false, file }); return c.json({ ok: true }); });
admin.delete("/user/:id/archive/:fileId", async (c) => { const found: any = await rpc(c.env.INDEX, "global", "file", { id: c.req.param("fileId") }); if (!found || found.owner_id !== c.req.param("id") || !found.archived) return c.json({ error: "not found" }, 404); await rpc(c.env.INDEX, "global", "purge", { id: c.req.param("fileId") }); try { await rpc(c.env.FILES, c.req.param("fileId"), "wipe", { uid: found.owner_id }); } catch (e: any) { console.error("admin wipe failed", c.req.param("fileId"), e?.message ?? e); return c.json({ error: "could not wipe file" }, 503); } return c.json({ ok: true }); });
admin.post("/user/:id/:action", async (c) => { const action = c.req.param("action"); if (action !== "ban" && action !== "unban") return c.json({ error: "unsupported action" }, 400); return c.json(await rpc(c.env.INDEX, "global", "ban", { id: c.req.param("id"), banned: action === "ban" })); });
admin.delete("/user/:id", async (c) => { const id = c.req.param("id"); const files = await rpc(c.env.INDEX, "global", "files", { uid: id, archived: "all" }) as SheetFile[]; for (const f of files) { try { await rpc(c.env.FILES, f.id, "wipe", { uid: id }); } catch (e: any) { console.error("admin user wipe failed", f.id, e?.message ?? e); } } return c.json(await rpc(c.env.INDEX, "global", "deleteUser", { id })); });
const findFile = async (c: any, id: string) => { const found: any = await rpc(c.env.INDEX, "global", "file", { id }); return found ? { owner: String(found.owner_id), archived: !!found.archived, file: JSON.parse(found.data) as SheetFile } : null; };
admin.get("/file/:id", async (c) => { const f = await findFile(c, c.req.param("id")); if (!f) return c.json({ error: "file not found" }, 404); const s = await rpc(c.env.FILES, f.file.id, "seq").catch(() => ({ seq: 0 })) as any; return c.json({ ...f.file, seq: Number(s?.seq ?? 0) }); });
admin.put("/file/:id", async (c) => { const f = await findFile(c, c.req.param("id")); if (!f) return c.json({ error: "file not found" }, 404); const body = await c.req.json<Record<string, unknown>>(); for (const k of ["name", "type", "columns", "password", "poolEnabled"]) if (k in body) (f.file as any)[k] = body[k]; f.file.updatedAt = Date.now(); f.file.lastAction = "modified"; await rpc(c.env.FILES, f.file.id, "save", { file: f.file }); await rpc(c.env.INDEX, "global", "register", { uid: f.owner, file: f.file }); if ((body as any).poolEnabled === false && (f.file as any).password) { try { const rows = await rpc(c.env.FILES, f.file.id, "rows").catch(() => [] as any[]) as any[]; await removePoolRows(c.env, (f.file as any).password, rows, f.owner, f.file); } catch (e: any) { console.error("pool disable cleanup failed", f.file.id, e?.message ?? e); } } return c.json(f.file); });
admin.delete("/file/:id", async (c) => { const f = await findFile(c, c.req.param("id")); if (!f) return c.json({ error: "file not found" }, 404); f.file.deletedAt = Date.now(); f.file.lastAction = "archived"; await rpc(c.env.INDEX, "global", "archive", { id: f.file.id, archived: true, file: f.file }); return c.json({ ok: true }); });
admin.get("/file/:id/rows", async (c) => { const f = await findFile(c, c.req.param("id")); if (!f) return c.json({ error: "file not found" }, 404); const rows = await rpc(c.env.FILES, f.file.id, "rows") as any[]; return c.json(await decorateHoldState(c.env, (f.file as any).password, rows)); });
admin.put("/file/:id/persist", async (c) => { const f = await findFile(c, c.req.param("id")); if (!f) return c.json({ error: "file not found" }, 404); const body = await c.req.json<{ rows?: any[]; action?: string; dataCount?: number; base?: unknown }>(); const rows = body.rows || []; if (rows.length > FILE_ROW_LIMIT) return c.json({ error: "too many rows (max 500 per file)" }, 400); if (body.base !== undefined && !Number.isInteger(body.base)) return c.json({ error: "invalid base" }, 400); let oldRows: any[]; try { oldRows = await rpc(c.env.FILES, f.file.id, "rows") as any[]; } catch { return c.json({ error: "could not read file rows" }, 503); } const newKeys = new Set(rows.map((r: any) => poolId(r)).filter(Boolean)); const removed = oldRows.filter((r: any) => { const k = poolId(r); return k && !newKeys.has(k); }); if (removed.length) { let h = 0; try { h = await heldInRows(c, f.file, removed); } catch { return c.json({ error: "could not verify hold state" }, 503); } if (h) return c.json(heldBlock(h), 409); } Object.assign(f.file, ldCounts(rows)); if (body.dataCount !== undefined) f.file.dataCount = body.dataCount; f.file.rowCount = rows.length; f.file.updatedAt = Date.now(); f.file.lastAction = "modified"; const saved = await rpc(c.env.FILES, f.file.id, "save", { file: f.file, rows, action: body.action || "edit", base: body.base }); await rpc(c.env.INDEX, "global", "register", { uid: f.owner, file: f.file }); const feed = selectFeedRows(oldRows, rows); if (feed.length) void feedPools(c.env, f.file, feed, f.owner); return c.json({ ok: true, seq: saved.seq, file: f.file }); });
// Admin restore: same hold-lock rule as owner restore — no special treatment.
admin.post("/file/:id/restore-snapshot", async (c) => { const f = await findFile(c, c.req.param("id")); if (!f) return c.json({ error: "file not found" }, 404); let snap: any; try { snap = await rpc(c.env.FILES, f.file.id, "snapGet"); } catch { return c.json({ error: "could not read snapshot" }, 503); } if (!snap) return c.json({ error: "no snapshot — nothing to restore yet" }, 404); let curRows: any[]; try { curRows = await rpc(c.env.FILES, f.file.id, "rows") as any[]; } catch { return c.json({ error: "could not read file rows" }, 503); } const snapKeys = new Set((snap.rows as any[]).map((r: any) => poolId(r)).filter(Boolean)); const removed = curRows.filter((r: any) => { const k = poolId(r); return k && !snapKeys.has(k); }); if (removed.length) { let h = 0; try { h = await heldInRows(c, f.file, removed); } catch { return c.json({ error: "could not verify hold state" }, 503); } if (h) return c.json(heldBlock(h), 409); } let index = 0; try { const b = await c.req.json<{ index?: unknown }>().catch(() => ({} as { index?: unknown })); if (b.index !== undefined) { if (!Number.isInteger(b.index) || (b.index as number) < 0) return c.json({ error: "invalid index" }, 400); index = b.index as number; } } catch { return c.json({ error: "invalid body" }, 400); } let out: any; try { out = await rpc(c.env.FILES, f.file.id, "snapRestore", { index }); } catch (e: any) { const m = String(e?.message || ""); if (m.includes("no snapshot")) return c.json({ error: "no snapshot — nothing to restore yet" }, 404); throw e; } await rpc(c.env.INDEX, "global", "register", { uid: f.owner, file: out.file }); if ((f.file as any).password) void feedPools(c.env, (f.file as any).password, out.rows, f.owner); return c.json({ ok: true, seq: out.seq, rows: out.rows, file: out.file }); });
admin.get("/file/:id/logs", async (c) => {
  const logs = await rpc(c.env.FILES, c.req.param("id"), "getLogs").catch(() => null) as any;
  if (Array.isArray(logs) && logs.length) return c.json(logs);
  // purged files cascade their logs away — serve the forensic tombstone instead.
  const tomb = await rpc(c.env.FILES, c.req.param("id"), "tombGet").catch(() => null);
  if (tomb) return c.json({ tombstoned: true, tomb });
  return c.json(logs ?? []);
});
admin.get("/file/:id/undo", async (c) => { const f = await findFile(c, c.req.param("id")); if (!f) return c.json({ error: "file not found" }, 404); return c.json({ undo: [], redo: [] }); });
admin.get("/pooldiag", async (c) => { const key = String(c.req.query("key") || "").trim().slice(0, 64); if (!key) return c.json({ error: "key required" }, 400); return c.json(await rpc(c.env.POOLS, "global", "diag", { key })); });
